<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>SotfModLoader</AssemblyName>
    <RootNamespace>SotfModLoader</RootNamespace>
    <Version>1.0.0</Version>
    <Product>Sons of the Forest Mod Loader</Product>
    <Company>JustinOros</Company>
    <Authors>JustinOros</Authors>
    <Description>Install, update and remove Sons of the Forest mods</Description>
    <Copyright>Copyright (c) 2026 Justin Oros</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <GenerateResourceUsePreserializedResources>false</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
